name: main-workflow

on:
  push:
    branches-ignore:
      - '!master'

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.x
          uses: actions/setup-python@v3
          with:
            python-version: '3.x'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run Test
          if: always()
#          run: python -m pytest tests/test_another_api.py
          run: python -m pytest --alluredir=./allure-results tests/test_another_api.py
          continue-on-error: true
        - name: Get Allure history
          uses: actions/checkout@v3
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages

        - name: Allure Report action from marketplace
          uses: simple-elf/allure-report-action@master
          if: always()
          with:
            allure_results: allure-results
            allure_history: allure-history

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-history
